In [3]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

In [4]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [5]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [6]:
import pandas as pd

In [7]:
df = pd.read_excel(r'C:\Users\LENOVO\Documents\sem5\Pattern Recognition\UAS_185314125\olahdata.xlsx')

In [8]:
df

VJ   TJ   GH  Status
0     2   68   41       3
1     0   35    0       3
2    19   54  114       3
3     2   10   13       2
4     2   15   63       3
5   144  131   53       3
6    78  135    0       1
7     1   13    0       3
8    17   25  157       2
9     0  147    0       1
10   85   19  101       3
11    4    1   19       2
12    2  115    0       3
13  157   50    0       3
14  111   79    0       2
15    1   25  109       1
16   52   16    7       3
17    2   35    0       3
18   39   15    1       1

In [9]:
x = df.iloc[:, 0:3].values
y = df.iloc[:, 3].values

In [10]:
x

array([[  2,  68,  41],
       [  0,  35,   0],
       [ 19,  54, 114],
       [  2,  10,  13],
       [  2,  15,  63],
       [144, 131,  53],
       [ 78, 135,   0],
       [  1,  13,   0],
       [ 17,  25, 157],
       [  0, 147,   0],
       [ 85,  19, 101],
       [  4,   1,  19],
       [  2, 115,   0],
       [157,  50,   0],
       [111,  79,   0],
       [  1,  25, 109],
       [ 52,  16,   7],
       [  2,  35,   0],
       [ 39,  15,   1]], dtype=int64)

In [11]:
y

array([3, 3, 3, 2, 3, 3, 1, 3, 2, 1, 3, 2, 3, 3, 2, 1, 3, 3, 1],
      dtype=int64)

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.5, random_state=42)

In [13]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
knn = KNeighborsClassifier(n_neighbors = 1, metric = 'manhattan',
                           weights = 'uniform', algorithm = 'ball_tree', leaf_size=5)
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='ball_tree', leaf_size=5, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [15]:
y_pred=knn.predict(x_test)

In [16]:
y_pred

array([3, 1, 3, 3, 3, 1, 3, 2, 3, 3], dtype=int64)

In [17]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         3
           3       0.43      0.50      0.46         6

    accuracy                           0.30        10
   macro avg       0.14      0.17      0.15        10
weighted avg       0.26      0.30      0.28        10



In [28]:
from sklearn.model_selection import TimeSeriesSplit

In [29]:
tscv = TimeSeriesSplit()
TimeSeriesSplit(max_train_size=None, n_splits=3)

TimeSeriesSplit(max_train_size=None, n_splits=3)

In [30]:
for train_index, test_index in tscv.split(x):
    print("TRAIN (index data):", train_index, "TEST (index data):", test_index)
    X_train, X_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    knn = KNeighborsClassifier(n_neighbors = 3, metric = 'manhattan',
                           weights = 'uniform', algorithm = 'ball_tree', leaf_size=5)
    knn.fit(X_train, y_train)
    y_pred=knn.predict(X_test)
    print("hasil prediksi:", y_pred)
    print(metrics.classification_report(y_test, y_pred),"\n")

TRAIN (index data): [0 1 2 3] TEST (index data): [4 5 6]
hasil prediksi: [3 3 3]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           3       0.67      1.00      0.80         2

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3
 

TRAIN (index data): [0 1 2 3 4 5 6] TEST (index data): [7 8 9]
hasil prediksi: [3 3 3]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       0.33      1.00      0.50         1

    accuracy                           0.33         3
   macro avg       0.11      0.33      0.17         3
weighted avg       0.11      0.33      0.17         3
 

TRAIN (index data): [0 1 2 3 4 5 6 7 8 9] TEST (index data): [10 11 12]
hasil prediksi: [3 3 3]
              precision 

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\

In [18]:
df2 = pd.read_excel(r'C:\Users\LENOVO\Documents\sem5\Pattern Recognition\UAS_185314125\data pred baru.xlsx')

In [19]:
df2

VJ  TJ  GH  Status
0  49  92   7       2

In [20]:
x_test = df2.iloc[:, 0:3].values
y_test = df2.iloc[:, 3].values

In [21]:
x_test

array([[49, 92,  7]], dtype=int64)

In [22]:
y_pred=knn.predict(x_test)
y_pred

array([3], dtype=int64)